<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo [
    <!ELEMENT catalogo (pelicula+)>
    <!ELEMENT pelicula (titulo, director, año, genero)>
    <!ATTLIST pelicula id ID #REQUIRED>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT director (#PCDATA)>
    <!ELEMENT año (#PCDATA)>
    <!ELEMENT genero (#PCDATA)>
]>
<catalogo>
    <pelicula id="pelicula1">
        <titulo>Inception</titulo>
        <director>Christopher Nolan</director>
        <año>2010</año>
        <genero>Ciencia Ficción</genero>
    </pelicula>
</catalogo>